### ISSUE TITLE
CreateAdditionalServerID and domino_java_tools Refactoring

### ISSUE THREAD

**Issue by JoelProminic** [STARTcloud/hcl_roles#10]
We would like to get CreateAdditionalServerID.java class/jar added to the [domino_java_tools role](https://github.com/STARTcloud/hcl_roles/tree/main/roles/domino_java_tools/files).

If we are going to treat this as the official source for these Java files, I'd like to refactor the files so that they can be edited and maintained with Moonshine-IDE.  These files are currently in a different directory and templated:
- https://github.com/STARTcloud/hcl_roles/blob/main/roles/domino_java_tools/templates/CrossCertifyNotesID.java.j2
- https://github.com/STARTcloud/hcl_roles/blob/main/roles/domino_java_tools/templates/build.gradle.j2

The inserion parameters should be converted to properties that can be provided as Gradle parameters or in [the properties file](https://github.com/STARTcloud/hcl_roles/blob/main/roles/domino_java_tools/templates/CrossCertifyNotesID.properties.j2)

UPDATE:  Branch:  https://github.com/STARTcloud/hcl_roles/tree/features/issue_10_domino_java_tools

**Comment by JoelProminic** [comment]
@MarkProminic, I have the initial updates done for this.   I haven't tested the Ansible updates yet - I may need some help getting a v0.1.23 environment set up.

**Comment by JoelProminic** [comment]
I did an initial test with this, and it generated an ID without errors.  However, I couldn't access names.nsf to check the server document because of cross-certificate errors.

I think I also need to add a check to make sure that the additional server name doesn't exist already.  I can run CreateAdditionalServerID multiple times with the same parameters without errors, but I suspect it is creating duplicate server documents, which may cause headaches later.

**Comment by JoelProminic** [comment]
I ran into some trouble with CreateAdditionalServerID.  If I set [server.id.password](https://github.com/STARTcloud/hcl_roles/blob/dd7e9013b97ddd15125dc5601c9194e1478d0341/roles/domino_java_tools/files/src/main/java/net/prominic/domino/vagrant/CreateAdditionalServerID.java#L84) to a password, then we require a password for [setup.json]() and also on Domino startup:

    [070682:000002-00007FF215B11740] HCL Domino (r) Server (64 Bit), Release 12.0.1, November 22, 2021
    [070682:000002-00007FF215B11740] (C) Copyright HCL Technologies. 1987, 2021

    [070682:000002-00007FF215B11740] Performing consistency check on names.nsf...
    [070682:000002-00007FF215B11740] Completed consistency check on names.nsf
    [070682:000002-00007FF215B11740] The ID file being used is: /local/notesdata/server.id
    [070682:000002-00007FF215B11740] Enter password (press the Esc key to abort):

However, if I set the password to "" or force it to be `null`, I get this error:

    NotesException: Notes error: No password specified (test-additional-2.shi.com)
            at lotus.domino.local.Registration.NregisterNewServer(Native Method)
            at lotus.domino.local.Registration.registerNewServer(Unknown Source)
            at net.prominic.domino.vagrant.CreateAdditionalServerID.main(CreateAdditionalServerID.java:123)

Some things I have investigated:
- I did not find any instructions to exclude the password in the [Domino API](https://help.hcl-software.com/dom_designer/12.0.0/basic/H_REGISTERNEWSERVER_METHOD_JAVA.html)
- I don't see a constant to use to request no password
- TODO:  Try using the alternative forms (different number of arguments) for registerNewServer
- TODO: I found that Daniel Nashed's service script has an option to [input the password from a file](https://github.com/nashcom/domino-startscript/blob/acc1e6a0bf8e752221087e7b55e77f271c7f836f/rc_domino_script#L2703).  I think that JeDI can also support this with DominoServerPassword in etc/partitions.xml

**Comment by JoelProminic** [comment]
@JustinProminic suggested that I change the minimum password length on this line:
https://github.com/STARTcloud/hcl_roles/blob/dd7e9013b97ddd15125dc5601c9194e1478d0341/roles/domino_java_tools/files/src/main/java/net/prominic/domino/vagrant/CreateAdditionalServerID.java#L117

**Comment by JoelProminic** [comment]
Unfortunately, setMinPasswordLength](https://help.hcl-software.com/dom_designer/12.0.0/basic/H_MINPASSWORDLENGTH_PROPERTY_JAVA.html) did not clear the error.  From the documentation, this property seems to actually be "minimum password strength" and 0 means that the password is optional.  However I still get the password error if I set the value to 0, or use the default (which is also 0):

```
Original MinPasswordLength:  0
Updated MinPasswordLength:  0
NotesException: Notes error: No password specified (test-additional-3.shi.com)
	at lotus.domino.local.Registration.NregisterNewServer(Native Method)
	at lotus.domino.local.Registration.registerNewServer(Unknown Source)
	at net.prominic.domino.vagrant.CreateAdditionalServerID.main(CreateAdditionalServerID.java:134)
```

```
			reg.setIDType(Registration.ID_HIERARCHICAL);
			// password strength.  0 means that the password is optional
			// https://help.hcl-software.com/dom_designer/12.0.0/basic/H_MINPASSWORDLENGTH_PROPERTY_JAVA.html
			System.out.println("Original MinPasswordLength:  " + reg.getMinPasswordLength());
			reg.setMinPasswordLength(0); 
			System.out.println("Updated MinPasswordLength:  " + reg.getMinPasswordLength());
			reg.setNorthAmerican(true);
			//reg.setOrgUnit("AceHardwareNE");
			reg.setRegistrationLog("log.nsf");
			reg.setUpdateAddressBook(true);
			reg.setStoreIDInAddressBook(true);
			if (reg.registerNewServer(additionalServerName, // server name
				outputIDFile, // file to be created
				domainName, // domain name
				additionalServerPassword, // password for server ID
				certIDPassword, // certifier password
				"", // location field
				"", // comment field
				"", // Notes named network
				serverAdministrator, // server administrator
				additionalServerTitle)) // Domino Directory title field
			{ 
				System.out.println("Registration succeeded!  Server ID created at:  " + outputIDFile); 
			}
			else { 
				System.out.println("Registration failed"); 
			}
```

I'll keep investigating.  I feel like I am missing something obvious...

**Comment by JoelProminic** [comment]
I revisited this task.  I merged main into the branch, and updated build.gradle.

One problem was that the new lwpd.domino.napi.jar`` and `lwpd.commons.jar` dependencies were in inconsistent locations (even compared to Notes.jar).

    # macOS 14.0.0
    # identical
    /Applications/HCL Notes.app/Contents/Eclipse/shared/eclipse/plugins/com.ibm.domino.napi_12.0.2.20231104-0931/lwpd.domino.napi.jar
    /Applications/HCL Notes.app/Contents/Resources/ndext/lwpd.domino.napi.jar

    /Applications/HCL Notes.app/Contents/Resources/ndext/lwpd.commons.jar


    # macOS 12.0.1 FP1
    joelanderson@Joels-Mac-mini files % find "/Applications/HCL Notes.app" -name lwpd.domino.napi.jar         
    /Applications/HCL Notes.app/Contents/Eclipse/shared/eclipse/plugins/com.ibm.domino.napi_12.0.1.20211117-2131/lwpd.domino.napi.jar
    /Applications/HCL Notes.app/Contents/Eclipse/shared/eclipse/plugins/com.ibm.domino.napi_12.0.1.20220404-1552/lwpd.domino.napi.jar
    joelanderson@Joels-Mac-mini files % find "/Applications/HCL Notes.app" -name lwpd.commons.jar    
    /Applications/HCL Notes.app/Contents/Eclipse/shared/eclipse/plugins/com.ibm.commons_12.0.1.20211117-2131/lwpd.commons.jar
    /Applications/HCL Notes.app/Contents/Eclipse/shared/eclipse/plugins/com.ibm.commons_12.0.1.20220404-1552/lwpd.commons.jar


    # Linux 14.0
    startcloud@test-jedi-14:~/update/jedi$ sudo find /opt/hcl/domino/notes/latest/linux/ -name "lwpd.domino.napi.jar"
    /opt/hcl/domino/notes/latest/linux/ndext/lwpd.domino.napi.jar
    startcloud@test-jedi-14:~/update/jedi$ sudo find /opt/hcl/domino/notes/latest/linux/ -name "lwpd.commons.jar"
    /opt/hcl/domino/notes/latest/linux/ndext/lwpd.commons.jar
    /opt/hcl/domino/notes/latest/linux/osgi/shared/eclipse/plugins/com.ibm.commons_12.0.2.20241115-0934/lwpd.commons.jar



    # Linux 12.0.2
    startcloud@test-1202:~$ sudo find /opt/hcl/domino/ -name lwpd.domino.napi.jar
    /opt/hcl/domino/notes/12000200/linux/jvm/lib/ext/lwpd.domino.napi.jar
    /opt/hcl/domino/notes/12000200/linux/jvm/lib/ext/1202FP2/lwpd.domino.napi.jar
    startcloud@test-1202:~$ sudo find /opt/hcl/domino/ -name lwpd.commons.jar
    /opt/hcl/domino/notes/12000200/linux/jvm/lib/ext/lwpd.commons.jar
    /opt/hcl/domino/notes/12000200/linux/jvm/lib/ext/1202FP2/lwpd.commons.jar
    /opt/hcl/domino/notes/12000200/linux/osgi/shared/eclipse/plugins/com.ibm.commons_12.0.2.20230629-1845/lwpd.commons.jar


    # Linux 12.0.1
        implementation files("$notesInstallation/osgi/shared/eclipse/plugins/com.ibm.domino.napi_12.0.1.20211117-2131/lwpd.domino.napi.jar")
        implementation files("$notesInstallation/osgi/shared/eclipse/plugins/com.ibm.commons_12.0.1.20211117-2131/lwpd.commons.jar)


I added some logic to search for these JARs.  Tests:

OS | Domino | JARs found
-- | -- | --
macOS | 14.0 | Works
macOS | 12.0.1 | Works
Linux | 14.0 | Works
Linux | 12.0.1 | Works
Linux | 12.0.2 | Works

**Comment by JoelProminic** [comment]
I generated an additional server ID and confirmed I could use it to create a new server.  I'm satisfied with the updates, so I have updated hcl_roles and hcl_domino_standalone_provisioners.
